        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 03 14:38:22 2013
        MODULE AGGREGATEDOUTNUM__genmod
          INTERFACE 
            SUBROUTINE AGGREGATEDOUTNUM(AGGOUTCONTROL,OUTSYMBOL,        &
     &AGGOUTNUM)
              CHARACTER(LEN=200) :: AGGOUTCONTROL
              CHARACTER(LEN=200) :: OUTSYMBOL(66)
              INTEGER(KIND=4) :: AGGOUTNUM
            END SUBROUTINE AGGREGATEDOUTNUM
          END INTERFACE 
        END MODULE AGGREGATEDOUTNUM__genmod
