        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 03 14:38:24 2013
        MODULE CHECK__genmod
          INTERFACE 
            SUBROUTINE CHECK(STATUS)
              INTEGER(KIND=4), INTENT(IN) :: STATUS
            END SUBROUTINE CHECK
          END INTERFACE 
        END MODULE CHECK__genmod
