        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 03 14:38:21 2013
        MODULE CHECKS__genmod
          INTERFACE 
            SUBROUTINE CHECKS(SVFILE,ISINPUTFROMNC,NUMNCFILES,TOTALNC,  &
     &STATESITEVNAME)
              CHARACTER(LEN=200) :: SVFILE
              INTEGER(KIND=4) :: ISINPUTFROMNC(11)
              INTEGER(KIND=4) :: NUMNCFILES(11)
              INTEGER(KIND=4) :: TOTALNC
              CHARACTER(LEN=200) :: STATESITEVNAME(32)
            END SUBROUTINE CHECKS
          END INTERFACE 
        END MODULE CHECKS__genmod
