        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 03 14:38:22 2013
        MODULE DIRECTORYCREATE__genmod
          INTERFACE 
            SUBROUTINE DIRECTORYCREATE(NREFYR,NREFMO,NREFDAY,           &
     &WATERSHEDFILE,WSYCOORDINATE,WSXCOORDINATE,NUMOFFILE,OUTCOUNT,     &
     &OUTVAR,NUMTIMESTEPPERFILE,OUTSAMPLEFILE,OUTPUTNCCONTAINER,        &
     &NCIDARRAY)
              INTEGER(KIND=4) :: OUTCOUNT
              INTEGER(KIND=4) :: NUMOFFILE
              INTEGER(KIND=4) :: NREFYR
              INTEGER(KIND=4) :: NREFMO
              INTEGER(KIND=4) :: NREFDAY
              CHARACTER(LEN=200) :: WATERSHEDFILE
              CHARACTER(LEN=50) :: WSYCOORDINATE
              CHARACTER(LEN=50) :: WSXCOORDINATE
              INTEGER(KIND=4) :: OUTVAR(OUTCOUNT)
              INTEGER(KIND=4) :: NUMTIMESTEPPERFILE(NUMOFFILE)
              CHARACTER(LEN=200) :: OUTSAMPLEFILE(OUTCOUNT)
              CHARACTER(LEN=200) :: OUTPUTNCCONTAINER(NUMOFFILE,OUTCOUNT&
     &)
              INTEGER(KIND=4) :: NCIDARRAY(NUMOFFILE,OUTCOUNT)
            END SUBROUTINE DIRECTORYCREATE
          END INTERFACE 
        END MODULE DIRECTORYCREATE__genmod
