        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 03 14:38:24 2013
        MODULE FINDDIMENSIONLENGTH__genmod
          INTERFACE 
            SUBROUTINE FINDDIMENSIONLENGTH(FILE_NAME,DIMNAME1,DIMNAME2, &
     &DIMLEN1,DIMLEN2)
              CHARACTER(LEN=50) :: FILE_NAME
              CHARACTER(LEN=50) :: DIMNAME1
              CHARACTER(LEN=50) :: DIMNAME2
              INTEGER(KIND=4) :: DIMLEN1
              INTEGER(KIND=4) :: DIMLEN2
            END SUBROUTINE FINDDIMENSIONLENGTH
          END INTERFACE 
        END MODULE FINDDIMENSIONLENGTH__genmod
