        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 03 14:38:24 2013
        MODULE LOWERCASE__genmod
          INTERFACE 
            SUBROUTINE LOWERCASE(STR,LCSTR)
              CHARACTER(*) :: STR
              CHARACTER(LEN=LEN_TRIM(STR)) :: LCSTR
            END SUBROUTINE LOWERCASE
          END INTERFACE 
        END MODULE LOWERCASE__genmod
