        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 03 14:38:21 2013
        MODULE NCCHECKS__genmod
          INTERFACE 
            SUBROUTINE NCCHECKS(SVFILE,STATESITEVNAME,WATERSHEDFILE,    &
     &MAXNUMOFFILE,ISINPUTFROMNC,NCDFCONTAINER,NUMNCFILES,TOTALNC,      &
     &ALLNCDFFILE,INPUTXCOORDINATES,INPUTYCOORDINATES,SITEXCOORDINATES, &
     &SITEYCOORDINATES,WSXCOORDINATE,WSYCOORDINATE)
              INTEGER(KIND=4) :: TOTALNC
              INTEGER(KIND=4) :: MAXNUMOFFILE
              CHARACTER(LEN=200) :: SVFILE
              CHARACTER(LEN=200) :: STATESITEVNAME(32)
              CHARACTER(LEN=200) :: WATERSHEDFILE
              INTEGER(KIND=4) :: ISINPUTFROMNC(11)
              CHARACTER(LEN=200) :: NCDFCONTAINER(MAXNUMOFFILE,32)
              INTEGER(KIND=4) :: NUMNCFILES(11)
              CHARACTER(LEN=200) :: ALLNCDFFILE(TOTALNC)
              CHARACTER(LEN=50) :: INPUTXCOORDINATES(11)
              CHARACTER(LEN=50) :: INPUTYCOORDINATES(11)
              CHARACTER(LEN=50) :: SITEXCOORDINATES(32)
              CHARACTER(LEN=50) :: SITEYCOORDINATES(32)
              CHARACTER(LEN=50) :: WSXCOORDINATE
              CHARACTER(LEN=50) :: WSYCOORDINATE
            END SUBROUTINE NCCHECKS
          END INTERFACE 
        END MODULE NCCHECKS__genmod
