        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 03 14:38:24 2013
        MODULE NCDF3DARRAYINFO__genmod
          INTERFACE 
            SUBROUTINE NCDF3DARRAYINFO(FILE_NAME,DIMNAME1,DIMNAME2,     &
     &DIMNAME3,DIMLEN2,DIMLEN1,DIMLEN3)
              CHARACTER(LEN=50) :: FILE_NAME
              CHARACTER(LEN=50) :: DIMNAME1
              CHARACTER(LEN=50) :: DIMNAME2
              CHARACTER(LEN=50) :: DIMNAME3
              INTEGER(KIND=4) :: DIMLEN2
              INTEGER(KIND=4) :: DIMLEN1
              INTEGER(KIND=4) :: DIMLEN3
            END SUBROUTINE NCDF3DARRAYINFO
          END INTERFACE 
        END MODULE NCDF3DARRAYINFO__genmod
