        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 03 14:38:24 2013
        MODULE NCDF2DARRAYINFO__genmod
          INTERFACE 
            SUBROUTINE NCDF2DARRAYINFO(FILE_NAME,DIMNAME1,DIMNAME2,     &
     &DIMLEN2,DIMLEN1)
              CHARACTER(LEN=200) :: FILE_NAME
              CHARACTER(LEN=50) :: DIMNAME1
              CHARACTER(LEN=50) :: DIMNAME2
              INTEGER(KIND=4) :: DIMLEN2
              INTEGER(KIND=4) :: DIMLEN1
            END SUBROUTINE NCDF2DARRAYINFO
          END INTERFACE 
        END MODULE NCDF2DARRAYINFO__genmod
