        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 03 14:38:24 2013
        MODULE NCDF3DTIMEREAD__genmod
          INTERFACE 
            SUBROUTINE NCDF3DTIMEREAD(FILE_NAME,REC_NAME,TIME_POS,      &
     &TIME_VAL,NUMTIMESTEP,SYEAR,SMONTH,SDAY,DAYSSTRING)
              CHARACTER(LEN=50) :: FILE_NAME
              CHARACTER(LEN=50) :: REC_NAME
              INTEGER(KIND=4) :: TIME_POS
              REAL(KIND=8) :: TIME_VAL(1)
              INTEGER(KIND=4) :: NUMTIMESTEP
              INTEGER(KIND=4) :: SYEAR
              INTEGER(KIND=4) :: SMONTH
              INTEGER(KIND=4) :: SDAY
              CHARACTER(LEN=50) :: DAYSSTRING
            END SUBROUTINE NCDF3DTIMEREAD
          END INTERFACE 
        END MODULE NCDF3DTIMEREAD__genmod
