        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 03 14:38:24 2013
        MODULE NCDF2DREADREAL__genmod
          INTERFACE 
            SUBROUTINE NCDF2DREADREAL(FILE_NAME,VARNAME,SINGLEARRAY,J,I,&
     &SITEXCOORD,SITEYCOORD)
              CHARACTER(LEN=50) :: FILE_NAME
              CHARACTER(LEN=50) :: VARNAME
              REAL(KIND=4) :: SINGLEARRAY(1)
              INTEGER(KIND=4) :: J
              INTEGER(KIND=4) :: I
              CHARACTER(LEN=50) :: SITEXCOORD
              CHARACTER(LEN=50) :: SITEYCOORD
            END SUBROUTINE NCDF2DREADREAL
          END INTERFACE 
        END MODULE NCDF2DREADREAL__genmod
