        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 03 14:38:24 2013
        MODULE NCDF2DREADINTEGER__genmod
          INTERFACE 
            SUBROUTINE NCDF2DREADINTEGER(FILE_NAME,VARNAME,SINGLEARRAY,J&
     &,I,WSXCOORDINATE,WSYCOORDINATE)
              CHARACTER(LEN=50) :: FILE_NAME
              CHARACTER(LEN=50) :: VARNAME
              INTEGER(KIND=4) :: SINGLEARRAY(1)
              INTEGER(KIND=4) :: J
              INTEGER(KIND=4) :: I
              CHARACTER(LEN=50) :: WSXCOORDINATE
              CHARACTER(LEN=50) :: WSYCOORDINATE
            END SUBROUTINE NCDF2DREADINTEGER
          END INTERFACE 
        END MODULE NCDF2DREADINTEGER__genmod
