        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 03 14:38:22 2013
        MODULE NUMOUTFILES__genmod
          INTERFACE 
            SUBROUTINE NUMOUTFILES(OUTCONTROLFILE,MODELSTARTDATE,       &
     &MODELSTARTHOUR,MODELENDDATE,MODELENDHOUR,MODELDT,NUMTIMESTEP,     &
     &NUMOFFILE,NUMOUTPOINT,OUTCOUNT,DIMLEN1,DIMLEN2)
              CHARACTER(LEN=200) :: OUTCONTROLFILE
              INTEGER(KIND=4) :: MODELSTARTDATE(3)
              REAL(KIND=4) :: MODELSTARTHOUR
              INTEGER(KIND=4) :: MODELENDDATE(3)
              REAL(KIND=4) :: MODELENDHOUR
              REAL(KIND=4) :: MODELDT
              INTEGER(KIND=4) :: NUMTIMESTEP
              INTEGER(KIND=4) :: NUMOFFILE
              INTEGER(KIND=4) :: NUMOUTPOINT
              INTEGER(KIND=4) :: OUTCOUNT
              INTEGER(KIND=4) :: DIMLEN1
              INTEGER(KIND=4) :: DIMLEN2
            END SUBROUTINE NUMOUTFILES
          END INTERFACE 
        END MODULE NUMOUTFILES__genmod
