        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 03 14:38:24 2013
        MODULE READSVCOORDINATE__genmod
          INTERFACE 
            SUBROUTINE READSVCOORDINATE(SVFILE,SITEXCOORDINATES,        &
     &SITEYCOORDINATES)
              CHARACTER(LEN=50) :: SVFILE
              CHARACTER(LEN=50) :: SITEXCOORDINATES(32)
              CHARACTER(LEN=50) :: SITEYCOORDINATES(32)
            END SUBROUTINE READSVCOORDINATE
          END INTERFACE 
        END MODULE READSVCOORDINATE__genmod
