        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 03 14:38:24 2013
        MODULE STRINGSEP__genmod
          INTERFACE 
            SUBROUTINE STRINGSEP(STR,DELIMS,NARGS)
              CHARACTER(LEN=200) :: STR
              CHARACTER(LEN=1) :: DELIMS
              INTEGER(KIND=4) :: NARGS
            END SUBROUTINE STRINGSEP
          END INTERFACE 
        END MODULE STRINGSEP__genmod
