        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 03 14:38:24 2013
        MODULE STRINGSEPWORD__genmod
          INTERFACE 
            SUBROUTINE STRINGSEPWORD(STR,DELIMS,NARGS,WORD)
              INTEGER(KIND=4) :: NARGS
              CHARACTER(LEN=200) :: STR
              CHARACTER(LEN=1) :: DELIMS
              CHARACTER(LEN=200) :: WORD(NARGS)
            END SUBROUTINE STRINGSEPWORD
          END INTERFACE 
        END MODULE STRINGSEPWORD__genmod
