        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 03 14:38:23 2013
        MODULE VALUES4VAREACHGRID__genmod
          INTERFACE 
            SUBROUTINE VALUES4VAREACHGRID(INPUTVARNAME,ISINPUTFROMNC,   &
     &MAXNUMOFFILE,NUMNCFILES,NCDFCONTAINER,VARNAMEINNCDF,IYCOORD,      &
     &JXCOORD,NCFILENUMTIMESTEPS,NOOFTS,MAXNCFILENTS,ALLVALUES,         &
     &VARMISSINGVALUES,VARFILLVALUES,STEPINADAY,NUMTIMESTEP,            &
     &CURRENTARRAYPOSREGRID,REGRIDDEDARRAY,INPUTXCOORDINATES,           &
     &INPUTYCOORDINATES,INPUTTCOORDINATES,INPUTVARRANGE,INPVALS)
              INTEGER(KIND=4) :: NUMTIMESTEP
              INTEGER(KIND=4) :: MAXNCFILENTS
              INTEGER(KIND=4) :: MAXNUMOFFILE
              CHARACTER(LEN=200) :: INPUTVARNAME(11)
              INTEGER(KIND=4) :: ISINPUTFROMNC(11)
              INTEGER(KIND=4) :: NUMNCFILES(11)
              CHARACTER(LEN=200) :: NCDFCONTAINER(MAXNUMOFFILE,11)
              CHARACTER(LEN=100) :: VARNAMEINNCDF(11)
              INTEGER(KIND=4) :: IYCOORD
              INTEGER(KIND=4) :: JXCOORD
              INTEGER(KIND=4) :: NCFILENUMTIMESTEPS(MAXNUMOFFILE,11)
              INTEGER(KIND=4) :: NOOFTS(11)
              REAL(KIND=4) :: ALLVALUES(MAXNCFILENTS,11)
              REAL(KIND=4) :: VARMISSINGVALUES(MAXNUMOFFILE,11)
              REAL(KIND=4) :: VARFILLVALUES(MAXNUMOFFILE,11)
              INTEGER(KIND=4) :: STEPINADAY
              INTEGER(KIND=4) :: CURRENTARRAYPOSREGRID(NUMTIMESTEP,11)
              REAL(KIND=4) :: REGRIDDEDARRAY(NUMTIMESTEP,11)
              CHARACTER(LEN=50) :: INPUTXCOORDINATES(11)
              CHARACTER(LEN=50) :: INPUTYCOORDINATES(11)
              CHARACTER(LEN=50) :: INPUTTCOORDINATES(11)
              REAL(KIND=4) :: INPUTVARRANGE(11,2)
              REAL(KIND=4) :: INPVALS(11)
            END SUBROUTINE VALUES4VAREACHGRID
          END INTERFACE 
        END MODULE VALUES4VAREACHGRID__genmod
