        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 03 14:38:24 2013
        MODULE VARMISSFILL__genmod
          INTERFACE 
            SUBROUTINE VARMISSFILL(FILE_NAME,VARNAME,VARMISSINGVALUES,  &
     &VARFILLVALUES)
              CHARACTER(LEN=200) :: FILE_NAME
              CHARACTER(LEN=50) :: VARNAME
              REAL(KIND=4) :: VARMISSINGVALUES
              REAL(KIND=4) :: VARFILLVALUES
            END SUBROUTINE VARMISSFILL
          END INTERFACE 
        END MODULE VARMISSFILL__genmod
