        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 03 14:38:22 2013
        MODULE WSUNIQUEARRAY__genmod
          INTERFACE 
            SUBROUTINE WSUNIQUEARRAY(WATERSHEDFILE,WATERSHEDVARID,      &
     &DIMLEN1,DIMLEN2,UNIQUEIDNUMBER,UNIQUEIDARRAY,WSMISSINGVALUES,     &
     &WSFILLVALUES,UNIQUEIDARRAYCOUNT,WSXCOORDINATE,WSYCOORDINATE)
              INTEGER(KIND=4) :: UNIQUEIDNUMBER
              CHARACTER(LEN=200) :: WATERSHEDFILE
              CHARACTER(LEN=200) :: WATERSHEDVARID
              INTEGER(KIND=4) :: DIMLEN1
              INTEGER(KIND=4) :: DIMLEN2
              INTEGER(KIND=4) :: UNIQUEIDARRAY(UNIQUEIDNUMBER)
              REAL(KIND=4) :: WSMISSINGVALUES
              REAL(KIND=4) :: WSFILLVALUES
              INTEGER(KIND=4) :: UNIQUEIDARRAYCOUNT(UNIQUEIDNUMBER)
              CHARACTER(LEN=50) :: WSXCOORDINATE
              CHARACTER(LEN=50) :: WSYCOORDINATE
            END SUBROUTINE WSUNIQUEARRAY
          END INTERFACE 
        END MODULE WSUNIQUEARRAY__genmod
